### PR TITLE
Bump version to 4.1.0

### LINKED ISSUE #21: Create a new release for the 4.x branch with relax constraints
I'm unable to install the 4.0.0 release with Lumen 6.x and nordsoftware/lumen-newrelic 2.0.2 
This is already in the master. The 4.x.x release is just missing.

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #21 

No new changes, just tagging a new release

### CODE REVIEW

**Comment by hugovk** [comment]
Thanks!

**Comment by Jalle19** [comment]
Needs tagging as well @hugovk , unless you already did that

**Comment by hugovk** [comment]
I didn't, I can do it on Monday unless you can do it before that 👍

**Comment by hugovk** [comment]
https://github.com/digiaonline/lumen-contentful-sync/releases/tag/4.1.0 tagged!

**Pull request merged**
